In [1]:
#Exporatrory Data Analysis

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt

In [3]:
data=pd.read_csv(r"C:\Users\HP\Downloads\archive.zip")
print(data.head())

  User_ID Age  Gender         Country     User_Type Education_Level  \
0   U0269  30    Male  United Kingdom  Professional        Master's
1   U0217  30    Male   United States  Professional      Bachelor's
2   U0152  17    Male          Canada       Student             NaN
3   U0264  35  FEMALE          Brazil  Professional      Bachelor's
4   U0263  19  Female          Canada       Student   Undergraduate

                                        Profession Monthly_Income  \
0                                 Business Analyst           5421
1                      Customer Support Specialist           8903
2                         Computer Science Student            402
3  Desenvolvedora de Software / Software Developer           1367
4                                  Biology Student            438

         AI_Tool        AI_Purpose AI_Usage_Hours_Per_Day  \
0        ChatGPT       Office Work                  2 hrs
1        ChatGPT  Customer Support                    5.7
2       Chat GPT            Coding                  1 hrs
3        Meta AI            Coding                    1.7
4  Perplexity AI               NaN                    4.1

                                     Tasks_Performed Monthly_AI_Cost  \
0  Data analysis using AI-powered analytics tools...             NaN
1  Resolving customer inquiries using AI chatbot ...               0
2                                                NaN              20
3  Usar GitHub Copilot para autocompletar código,...              20
4  Using AI to generate study summaries for exam ...               0

   Productivity_Score  Accuracy_Rating  Satisfaction_Score  \
0                 5.3              4.0                 7.0
1                 9.9              3.0                 9.0
2                 3.2              2.0                 4.0
3                 5.6              4.0                 5.0
4                 4.7              4.0                 7.0

  Time_Saved_Hours_Per_Week Work_or_Study_Hours_Per_Day Would_Recommend
0                       3.9                         7.3             Yes
1                      11.4                     8.4 hrs             Yes
2                       5.2                         6.7              No
3                       6.4                         9.6           Maybe
4                       9.2                         6.2             Yes

In [4]:
data.describe()

       Productivity_Score  Accuracy_Rating  Satisfaction_Score
count          284.000000       285.000000          293.000000
mean             5.230282         3.428070            6.146758
std              1.817193         0.855338            1.517805
min              1.600000         2.000000            3.000000
25%              3.900000         3.000000            5.000000
50%              5.000000         4.000000            6.000000
75%              6.500000         4.000000            7.000000
max             10.000000         5.000000           10.000000

In [5]:
data.tail()

,User_ID,Age,Gender,Country,User_Type,Education_Level,Profession,Monthly_Income,AI_Tool,AI_Purpose,AI_Usage_Hours_Per_Day,Tasks_Performed,Monthly_AI_Cost,Productivity_Score,Accuracy_Rating,Satisfaction_Score,Time_Saved_Hours_Per_Week,Work_or_Study_Hours_Per_Day,Would_Recommend
295,U0066,NaN,Female,United States,Professional,Bachelor's,NaN,8255,Microsoft Copilot,NaN,1.8,"Code debugging with AI pair programming tools,...",0,1.8,3.0,4.0,NaN,12.2,No
296,U0094,43,Male,Nigeria,Professional,Diploma,Multimedia Content Producer,NaN,ChatGPT,Content Creation,1.2,Writing blog articles with AI writing assistan...,0,4.7,3.0,NaN,1,10.9,No
297,U0136,48,Male,Brazil,Professional,Diploma,Desenvolvedor de Sistemas (Systems Developer),544,Google Gemini,Coding,5.5,"Code debugging and optimization with AI tools,...",0,7.8,4.0,7.0,11.5,8.4,Yes
298,U0002,31,Female,Pakistan,Professional,Diploma,Junior Software Developer,448,ChatGPT,Coding,0.7 hrs,"Automated code generation using AI assistants,...",0,4.3,3.0,4.0,1.7,9.5,No
299,U0130,36 yrs,Male,United States,Professional,Diploma,Software Developer,6766,Chat GPT,Coding,2.8,"Debugging code with AI-assisted analysis, gene...",0,5.4,4.0,7.0,6.2,8.2,Yes

In [6]:
data.head()

,User_ID,Age,Gender,Country,User_Type,Education_Level,Profession,Monthly_Income,AI_Tool,AI_Purpose,AI_Usage_Hours_Per_Day,Tasks_Performed,Monthly_AI_Cost,Productivity_Score,Accuracy_Rating,Satisfaction_Score,Time_Saved_Hours_Per_Week,Work_or_Study_Hours_Per_Day,Would_Recommend
0,U0269,30,Male,United Kingdom,Professional,Master's,Business Analyst,5421,ChatGPT,Office Work,2 hrs,Data analysis using AI-powered analytics tools...,NaN,5.3,4.0,7.0,3.9,7.3,Yes
1,U0217,30,Male,United States,Professional,Bachelor's,Customer Support Specialist,8903,ChatGPT,Customer Support,5.7,Resolving customer inquiries using AI chatbot ...,0,9.9,3.0,9.0,11.4,8.4 hrs,Yes
2,U0152,17,Male,Canada,Student,NaN,Computer Science Student,402,Chat GPT,Coding,1 hrs,NaN,20,3.2,2.0,4.0,5.2,6.7,No
3,U0264,35,FEMALE,Brazil,Professional,Bachelor's,Desenvolvedora de Software / Software Developer,1367,Meta AI,Coding,1.7,"Usar GitHub Copilot para autocompletar código,...",20,5.6,4.0,5.0,6.4,9.6,Maybe
4,U0263,19,Female,Canada,Student,Undergraduate,Biology Student,438,Perplexity AI,NaN,4.1,Using AI to generate study summaries for exam ...,0,4.7,4.0,7.0,9.2,6.2,Yes

In [7]:
data.isna().sum()/len(data)*100

User_ID                        0.000000
Age                            7.666667
Gender                         3.333333
Country                        3.333333
User_Type                      0.000000
Education_Level                4.333333
Profession                     5.000000
Monthly_Income                 3.333333
AI_Tool                        3.666667
AI_Purpose                     4.333333
AI_Usage_Hours_Per_Day         2.333333
Tasks_Performed                6.000000
Monthly_AI_Cost                4.000000
Productivity_Score             5.333333
Accuracy_Rating                5.000000
Satisfaction_Score             2.333333
Time_Saved_Hours_Per_Week      3.333333
Work_or_Study_Hours_Per_Day    3.000000
Would_Recommend                1.666667
dtype: float64

In [8]:
data["Education_Level"].fillna(data["Education_Level"].mode()[0], inplace=True)
data["Education_Level"]

C:\Users\HP\AppData\Local\Temp\ipykernel_9636\4219719862.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data["Education_Level"].fillna(data["Education_Level"].mode()[0], inplace=True)

0           Master's
1         Bachelor's
2                NaN
3         Bachelor's
4      Undergraduate
           ...
295       Bachelor's
296          Diploma
297          Diploma
298          Diploma
299          Diploma
Name: Education_Level, Length: 300, dtype: str

In [9]:
data.shape

(300, 19)

In [11]:
data["ocean_proximity"]

KeyError: 'ocean_proximity'